services:
  {service_name}:
    image: {image_name}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # For Jupyter notebook if needed
    volumes:
      - ./:/app  # Mount current directory to /app
      - ./data:/app/data  # Mount data directory separately
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - data/
        - action: rebuild
          path: requirements.txt